### ISSUE TITLE
1.2.0 版本，相册展示，不会默认滚动到最下面了，是什么原因？

### ISSUE THREAD

**Issue by chenchangjun321** [heroims/ZYQAssetPickerController#18]
1.2.0 版本，相册展示的时候，不会默认滚动到最下面了，可以解决一下这个问题吗？
一样情况下，最新的照片在下面，但是如果照片很多的话，要用户自己滑动到最下面。可不可以自己默认就显示最下面的照片？

**Comment by linZsama** [comment]
> 1.2.0 版本，相册展示的时候，不会默认滚动到最下面了，可以解决一下这个问题吗？
> 一样情况下，最新的照片在下面，但是如果照片很多的话，要用户自己滑动到最下面。可不可以自己默认就显示最下面的照片？

请问你解决了吗??如何解决的

**Comment by heroims** [comment]
没切到主线程导致的，新版本已修复
