### ISSUE TITLE
[ZYQAsset valueForProperty:]崩溃

### ISSUE THREAD

**Issue by qpc2015** [heroims/ZYQAssetPickerController#19]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ZYQAsset valueForProperty:]: unrecognized selector sent to instance 0x283ee0040'

**Comment by heroims** [comment]
检查你的代码怎么使用的ZYQAsset，他不是系统的ALAsset，不提供valueForProperty
