### ISSUE TITLE
IOS 8.4使用内存检测发现内存泄露

### ISSUE THREAD

**Issue by money150604** [heroims/ZYQAssetPickerController#3]
![7b03d3c1-2025-448c-a7b4-f18100da5993](https://cloud.githubusercontent.com/assets/12742817/9704549/432d82e8-54de-11e5-8ddb-718b9e0bd70f.png)

**Comment by onesmalldog** [comment]
我也监测出这里有泄漏，请问怎么解决？

**Comment by heroims** [comment]
最新版已解决
