### ISSUE TITLE
访问iCloud图片

### ISSUE THREAD

**Issue by tiantiankaixin** [heroims/ZYQAssetPickerController#8]
当图片来自iCloud的时候，一开始只能拿到一个较小尺寸的缩略图，拿不到原图；怎么判断一张图正在从iCloud同步，然后给个提示；就像微信朋友圈那样，不让选中图片而是给个提示照片正在从iCloud下载..

**Comment by zgjun** [comment]
我也遇到了同样的问题，有什么好的办法可以解决？感谢！

**Comment by tiantiankaixin** [comment]
没管，我们需求是选图后上传，没从iCloud同步完取原图为空就直接跳过传下一张..@zgjun

**Comment by graygrayh** [comment]
当图片来自iCloud的时候,传回照片为空，此时如何获取原图，确实是个问题，现在使用缩略图

**Comment by heroims** [comment]
`[asset setGetFullScreenImage:^(UIImage *result) {
                 dispatch_async(dispatch_get_main_queue(), ^{
                     [imgview setImage:result];
                     [src addSubview:imgview];
                 });
  } fromNetwokProgressHandler:^(double progress, NSError *error, BOOL *stop, NSDictionary *info) {
               NSLog(@"下载中%f",progress);
             }];`
利用fromNetwokProgressHandler可以监控进度
